pipeline {
    agent {
      label 'docker'
    }


    stages {
        

        stage('Building the docker image') {
            steps {
                sh 'cd webapp && docker build -t abhisheksaya/frontend-lms .'
            }
        }

         stage('Running the docker container') {
            steps {
                  sh 'docker container rm --force fe'
                  sh 'docker run -dt -p 8000:80 --name fe abhisheksaya/frontend-lms'
            }
        }
    }
}
