
pipeline {
    agent{
       label 'docker'
    }
    stages {
        
        
         stage('Building the docker image') {
            steps {
                sh 'cd api && docker build -t abhisheksaya/backend-lms .'
            }
        }
         stage('creating database container') {
             steps {
                 sh 'docker container rm --force lmsdb'
                 sh 'docker run -d -p 5432:5432 --network lmsnetwork -e  POSTGRES_PASSWORD=password --name lmsdb postgres'
            }
        }
         stage('Running the docker container') {
            steps {
                  sh 'docker container rm --force backend'
                  sh 'docker run -d -p 8080:8080 --network lmsnetwork -e DATABASE_URL=postgresql://postgres:password@lmsdb:5432/postgres --name backend -e PORT=8080 -e MODE=local  abhisheksaya/backend-lms'
            }
        }
    }
}

